version: "2"

services:
  # application
  api:
    build: .
    command: runserver migrate
    depends_on:
      - mysql
    ports:
      - "80:80"
      - "8000:8000"
    volumes:
      - ./app:/src/app
    environment:
      - DJANGO_DEBUG=true
      - CLOUDFILES_IMAGES_PREFIX=marc_images_
      - SNAP_AUTHENTICATION=false
      - SNAP_AUTHORIZATION=false
      - DATABASE_HOST=mysql
      - DATABASE_NAME=snapabledb
      - DATABASE_USER=snapableusr
      - DATABASE_PASSWORD=snapable12345
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ETCD_HOST=192.168.50.11
    entrypoint: /wait-for-it.sh mysql:3306 -- /entrypoint.sh

  worker:
    build: .
    command: worker
    depends_on:
      - mysql
    volumes:
      - ./app:/src/app
    environment:
      - DJANGO_DEBUG=true
      - CLOUDFILES_IMAGES_PREFIX=marc_images_
      - DATABASE_HOST=mysql
      - DATABASE_NAME=snapabledb
      - DATABASE_USER=snapableusr
      - DATABASE_PASSWORD=snapable12345
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ETCD_HOST=192.168.50.11
    entrypoint: /wait-for-it.sh mysql:3306 -- /entrypoint.sh

  beat:
    build: .
    command: beat
    depends_on:
      - mysql
    environment:
      - DJANGO_DEBUG=true
      - CLOUDFILES_IMAGES_PREFIX=marc_images_
      - DATABASE_HOST=mysql
      - DATABASE_NAME=snapabledb
      - DATABASE_USER=snapableusr
      - DATABASE_PASSWORD=snapable12345
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ETCD_HOST=192.168.50.11

  # third-party
  mysql:
    image: mysql:5.5
    ports:
      - "3306:3306" # to connect with an SQL client
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlpass
      - MYSQL_USER=snapableusr
      - MYSQL_PASSWORD=snapable12345
      - MYSQL_DATABASE=snapabledb

  redis:
    image: redis:3.0-alpine
