# application
api:
  build: .
  command: api migrate
  ports:
    - "80:80"
  links:
    - redis:rd
    - redis:celery
    - mysql:db
  environment:
    - DJANGO_DEBUG=true
    - CLOUDFILES_IMAGES_PREFIX=marc_images_
    - SNAP_AUTHENTICATION=false
    - SNAP_AUTHORIZATION=false

worker:
  build: .
  command: worker
  links:
    - redis:rd
    - redis:celery
    - mysql:db
  environment:
    - DJANGO_DEBUG=true
    - CLOUDFILES_IMAGES_PREFIX=marc_images_

beat:
  build: .
  command: beat
  links:
    - redis:rd
    - redis:celery
    - mysql:db
  environment:
    - DJANGO_DEBUG=true
    - CLOUDFILES_IMAGES_PREFIX=marc_images_

# third-party
mysql:
  image: mysql:5.5
  ports:
    - "3306" # to connect with an SQL client
  environment:
    - MYSQL_ROOT_PASSWORD=mysqlpass
    - MYSQL_USER=snapableusr
    - MYSQL_PASSWORD=snapable12345
    - MYSQL_DATABASE=snapabledb

redis:
  image: redis:3.0-alpine

flower:
  image: johncosta/flower
  command: flower --port=5555 --broker=redis://rd:6379/1
  links:
    - redis:rd
  ports:
    - "5555:5555"
