from account import AccountResource
from addon import AddonResource
from address import AddressResource
from album import AlbumResource
from event import EventResource
from eventaddon import EventAddonResource
from guest import GuestResource
from order import OrderResource
from package import PackageResource
from photo import PhotoResource
from type import TypeResource
from user import UserResource